# Generated by Django 6.0 on 2025-12-07 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieObjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='donations.categorieobjet')),
            ],
            options={
                'verbose_name': "Catégorie d'objet",
                'verbose_name_plural': "Catégories d'objets",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('type_materiel', models.CharField(max_length=200)),
                ('quantite', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('bon_etat', 'Bon état'), ('etat_moyen', 'État moyen'), ('a_reparer', 'À réparer')], default='bon_etat', max_length=20)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='dons/')),
                ('statut', models.CharField(choices=[('en_stock', 'En stock'), ('garde_meuble', 'Garde Meuble'), ('en_depot_vente', 'En dépôt-vente'), ('reserve', 'Réservé'), ('donne', 'Donné'), ('vendu', 'Vendu'), ('perime', 'Périmé/Détruit')], default='en_stock', max_length=20)),
                ('date_entree_stock', models.DateTimeField(auto_now_add=True)),
                ('lieu_stockage', models.CharField(blank=True, max_length=100)),
                ('valeur_estimee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_vente', models.DateField(blank=True, null=True)),
                ('acheteur', models.CharField(blank=True, max_length=255)),
                ('date_don', models.DateField(blank=True, null=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.categorieobjet')),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-date_entree_stock'],
            },
        ),
        migrations.CreateModel(
            name='DemandeDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('type_materiel', models.CharField(max_length=200)),
                ('description_besoin', models.TextField()),
                ('quantite_desiree', models.IntegerField(default=1)),
                ('urgence', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='moyenne', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('raison_refus', models.TextField(blank=True)),
                ('adresse_livraison', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('disponibilite_livraison', models.TextField(blank=True)),
                ('date_attribution', models.DateTimeField(blank=True, null=True)),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('categorie_recherchee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.categorieobjet')),
                ('membre_validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.membre')),
                ('participant_requerant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_dons', to='users.participant')),
                ('transporteur_livraison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.transporteur')),
                ('don_attribue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_attribuees', to='donations.don')),
            ],
            options={
                'verbose_name': 'Demande de don',
                'verbose_name_plural': 'Demandes de dons',
                'ordering': ['urgence', '-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='PropositionDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_proposition', models.DateTimeField(auto_now_add=True)),
                ('type_materiel', models.CharField(max_length=200)),
                ('quantite', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('bon_etat', 'Bon état'), ('etat_moyen', 'État moyen'), ('a_reparer', 'À réparer')], default='bon_etat', max_length=20)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='propositions/dons/')),
                ('adresse_ramassage', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('disponibilite_ramassage', models.TextField(help_text='Disponibilités pour le ramassage')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('annulee', 'Annulée'), ('ramassee', 'Ramassée par transporteur')], default='en_attente', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('raison_refus', models.TextField(blank=True)),
                ('date_ramassage', models.DateField(blank=True, null=True)),
                ('heure_ramassage', models.TimeField(blank=True, null=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.categorieobjet')),
                ('membre_validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.membre')),
                ('participant_donateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions_dons', to='users.participant')),
                ('transporteur_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.transporteur')),
            ],
            options={
                'verbose_name': 'Proposition de don',
                'verbose_name_plural': 'Propositions de dons',
                'ordering': ['-date_proposition'],
            },
        ),
        migrations.AddField(
            model_name='don',
            name='proposition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='don_realise', to='donations.propositiondon'),
        ),
    ]
