# Generated by Django 6.0 on 2025-12-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propositiondon',
            name='transporteur_statut',
            field=models.CharField(choices=[('acceptee', 'Acceptée par transporteur'), ('refusee', 'Refusée par transporteur')], default='en_attente', max_length=20),
        ),
    ]
