# Generated by Django 6.0 on 2025-12-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_propositiondon_transporteur_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propositiondon',
            name='statut',
        ),
        migrations.AddField(
            model_name='propositiondon',
            name='raison_refus_transporteur',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='propositiondon',
            name='transporteur_statut',
            field=models.CharField(choices=[('en_attente', 'En attente de réponse'), ('acceptee', 'Acceptée par transporteur'), ('refusee', 'Refusée par transporteur')], default='en_attente', max_length=20),
        ),
    ]
