# Generated by Django 6.0 on 2025-12-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_remove_propositiondon_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propositiondon',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('annulee', 'Annulée'), ('ramassee', 'Ramassée par transporteur')], default='en_attente', max_length=20),
        ),
    ]
