# Generated by Django 6.0 on 2025-12-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_propositiondon_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='propositiondon',
            name='donator_gives',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propositiondon',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('annulee', 'Annulée'), ('ramassee', 'Ramassée par transporteur'), ('terminee', 'Terminée')], default='en_attente', max_length=20),
        ),
    ]
